export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_STARTED = 'ADD_POST_STARTED';
export const ADD_POST_FAILURE = 'ADD_POST_STARTED';
export const GET_POST_STARTED = 'GET_POST_STARTED';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';
